#include<cmath>
int solution(int N) {
    // write your code in C++11 (g++ 4.8.2)
    //     int largest_gap=0;
    //         const int MAX_BIT = (int)(log(N)/log(2));
    //             int i = 0;
    //                
    //                    // find first '1'
    //                        while(((N>>i)&1)==0 && i<=MAX_BIT)
    //                                i++;
    //                                   
    //                                       while(i < MAX_BIT){
    //                                                  
    //                                                          int curr_gap = 0;
    //                                                                 
    //                                                                         // find next '0'
    //                                                                                 while(((N>>i)&1)==1 && i<=MAX_BIT) {
    //                                                                                             i++;
    //                                                                                                     }   
    //                                                                                                             //count zeros
    //                                                                                                                     while(((N>>i)&1)==0 && i<=MAX_BIT){
    //                                                                                                                                 i++;
    //                                                                                                                                             curr_gap++;
    //                                                                                                                                                     }   
    //                                                                                                                                                             if (i<=MAX_BIT && curr_gap > largest_gap)
    //                                                                                                                                                                         largest_gap = curr_gap;       
    //                                                                                                                                                                                
    //                                                                                                                                                                                    }
    //                                                                                                                                                                                       
    //                                                                                                                                                                                          
    //                                                                                                                                                                                              return largest_gap;
    //                                                                                                                                                                                              #include<cmath>
    //                                                                                                                                                                                              int solution(int N) {
    //                                                                                                                                                                                                  // write your code in C++11 (g++ 4.8.2)
    //                                                                                                                                                                                                      int largest_gap=0;
    //                                                                                                                                                                                                          const int MAX_BIT = (int)(log(N)/log(2));
    //                                                                                                                                                                                                              int i = 0;
    //                                                                                                                                                                                                                 
    //                                                                                                                                                                                                                     // find first '1'
    //                                                                                                                                                                                                                         while(((N>>i)&1)==0 && i<=MAX_BIT)
    //                                                                                                                                                                                                                                 i++;
    //                                                                                                                                                                                                                                    
    //                                                                                                                                                                                                                                        while(i < MAX_BIT){
    //                                                                                                                                                                                                                                                   
    //                                                                                                                                                                                                                                                           int curr_gap = 0;
    //                                                                                                                                                                                                                                                                  
    //                                                                                                                                                                                                                                                                          // find next '0'
    //                                                                                                                                                                                                                                                                                  while(((N>>i)&1)==1 && i<=MAX_BIT) {
    //                                                                                                                                                                                                                                                                                              i++;
    //                                                                                                                                                                                                                                                                                                      }   
    //                                                                                                                                                                                                                                                                                                              //count zeros
    //                                                                                                                                                                                                                                                                                                                      while(((N>>i)&1)==0 && i<=MAX_BIT){
    //                                                                                                                                                                                                                                                                                                                                  i++;
    //                                                                                                                                                                                                                                                                                                                                              curr_gap++;
    //                                                                                                                                                                                                                                                                                                                                                      }   
    //                                                                                                                                                                                                                                                                                                                                                              if (i<=MAX_BIT && curr_gap > largest_gap)
    //                                                                                                                                                                                                                                                                                                                                                                          largest_gap = curr_gap;       
    //                                                                                                                                                                                                                                                                                                                                                                                 
    //                                                                                                                                                                                                                                                                                                                                                                                     }
    //                                                                                                                                                                                                                                                                                                                                                                                        
    //                                                                                                                                                                                                                                                                                                                                                                                           
    //                                                                                                                                                                                                                                                                                                                                                                                               return largest_gap;
    //                                                                                                                                                                                                                                                                                                                                                                                               #include<cmath>
    //                                                                                                                                                                                                                                                                                                                                                                                               int solution(int N) {
    //                                                                                                                                                                                                                                                                                                                                                                                                   // write your code in C++11 (g++ 4.8.2)
    //                                                                                                                                                                                                                                                                                                                                                                                                       int largest_gap=0;
    //                                                                                                                                                                                                                                                                                                                                                                                                           const int MAX_BIT = (int)(log(N)/log(2));
    //                                                                                                                                                                                                                                                                                                                                                                                                               int i = 0;
    //                                                                                                                                                                                                                                                                                                                                                                                                                  
    //                                                                                                                                                                                                                                                                                                                                                                                                                      // find first '1'
    //                                                                                                                                                                                                                                                                                                                                                                                                                          while(((N>>i)&1)==0 && i<=MAX_BIT)
    //                                                                                                                                                                                                                                                                                                                                                                                                                                  i++;
    //                                                                                                                                                                                                                                                                                                                                                                                                                                     
    //                                                                                                                                                                                                                                                                                                                                                                                                                                         while(i < MAX_BIT){
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                    
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                            int curr_gap = 0;
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                           // find next '0'
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   while(((N>>i)&1)==1 && i<=MAX_BIT) {
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               i++;
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }   
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               //count zeros
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       while(((N>>i)&1)==0 && i<=MAX_BIT){
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   i++;
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               curr_gap++;
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }   
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               if (i<=MAX_BIT && curr_gap > largest_gap)
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           largest_gap = curr_gap;       
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return largest_gap;
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }}}
